export type FlowerCategory = "rose" | "tulip" | "sunflower" | "carnation" | "wedding" | "lily";

export interface Product {
  id: string;
  name: string;
  featured: boolean,
  category: FlowerCategory;
  categoryName: string;
  price: number;
  description: string;
  image: string;
  tint: string;
}

export const categories: { id: FlowerCategory | "all"; label: string }[] = [
  { id: "all", label: "همه گل‌ها" },
  { id: "rose", label: "رز | Rose" },
  { id: "tulip", label: "لاله | Tulip" },
  { id: "sunflower", label: "آفتاب‌گردان | Sunflower" },
  { id: "carnation", label: "میخک | Carnation" },
  { id: "lily", label: "لیلیوم | Lily" },
  { id: "wedding", label: "گل خواستگاری" },
];

export const products: Product[] = [
  {
    id: "rose-red",
    name: "رز سرخ شاهانه",
    featured: true,
    category: "rose",
    categoryName: "رز",
    price: 550,
    description: "دسته گل رز سرخ مخملی با عطری دل‌انگیز، نماد عشق ابدی.",
    image: "/assets/rose.jpg",
    tint: "var(--gradient-rose)",
  },
  {
    id: "rose-red-wedding",
    name: "رز سرخ",
    featured: false,
    category: "rose",
    categoryName: "رز",
    price: 250,
    description: "دسته‌گل رز سرخ تازه با گلبرگ‌های مخملی و رنگ عمیق، نماد عشق، احترام و احساسات صادقانه. مناسب برای عروسی، سالگرد و هدیه‌های رمانتیک.",
    image: "/assets/rose1.jpg",
    tint: "var(--gradient-rose)",
  },
  {
    id: "rose-red-garden",
    name: "باغ رؤیایی رز",
    featured: false,
    category: "rose",
    categoryName: "رز",
    price: 5000,
    description: "باغی سرسبز و چشم‌نواز از گل‌های رز سرخ با عطر دل‌انگیز که فضایی رمانتیک و آرامش‌بخش ایجاد می‌کند. مناسب برای مراسم عروسی، عکاسی و محفل‌های خاص.",
    image: "/assets/rose2.jpg",
    tint: "var(--gradient-rose)",
  },
  {
    id: "tulip-pink",
    name: "دسته گل لاله صورتی و سفید",
    featured: false,
    category: "tulip",
    categoryName: "لاله",
    price: 750,
    description: "دسته گل مجلل با ترکیب لاله‌های صورتی پررنگ و سفید کرمی هلندی، تزئین‌شده با شکوفه‌های ریز سفید و برگ‌های سبز، بسته‌بندی با روبان صورتی شیک — ایده‌آل برای هدیه‌های خاص و مناسبت‌های عاشقانه",
    image: "/assets/tulip.jpg",
    tint: "var(--gradient-tulip)",
  },
  {
    id: "tulip-pink-multicolors",
    name: "دسته گل لاله رنگارنگ بهاری",
    featured: false,
    category: "tulip",
    categoryName: "لاله",
    price: 1100,
    description: "دسته گل پرانرژی از لاله‌های هلندی در رنگ‌های بنفش، قرمز، زرد، سفید و صورتی، بسته‌بندی‌شده با کاغذ کرافت طبیعی — انتخابی شاد و بی‌نظیر برای هر مناسبتی.",
    image: "/assets/tulip2.jpg",
    tint: "var(--gradient-tulip)",
  },
  {
    id: "tulip-pink-garden",
    name: "لاله‌های مزرعه هلندی",
    featured: false,
    category: "tulip",
    categoryName: "لاله",
    price: 450,
    description: "الهام‌گرفته از مزارع رنگارنگ هلند — ردیف‌های چشم‌نواز لاله در رنگ‌های صورتی، زرد، قرمز و سفید، با تصویری رویایی از آسیاب بادی در غروب آفتاب.",
    image: "/assets/tulip4.jpg",
    tint: "var(--gradient-tulip)",
  },
  {
    id: "sunflower-bright",
    name: "دسته گل آفتابگردان و رز سفید",
    featured: false,
    category: "sunflower",
    categoryName: "آفتاب‌گردان",
    price: 800,
    description: "ترکیب گرم و شاد آفتابگردان‌های درشت طلایی با رزهای سفید ظریف، سبزه‌های تازه و شاخه‌های زرد کوچک، بسته‌بندی‌شده با کاغذ مشکی مدرن — هدیه‌ای پرانرژی و در عین حال شیک.",
    image: "/assets/sunflower.jpg",
    tint: "var(--gradient-sun)",
  },
  {
    id: "sunflower-bright-oneis",
    name: "دسته گل آفتابگردان و گل‌های وحشی",
    featured: true,
    category: "sunflower",
    categoryName: "آفتاب‌گردان",
    price: 600,
    description: "ترکیب دلنشین آفتابگردان‌های طلایی با گل‌های وحشی رنگارنگ — بابونه‌های سفید، گل‌های بنفش و صورتی ریز، و شاخه‌های صورتی کمرنگ، بسته‌بندی با کاغذ کرافت روستایی — حس طبیعت و آزادی را به خانه می‌آورد.",
    image: "/assets/sunflower3.jpg",
    tint: "var(--gradient-sun)",
  },
  {
    id: "sunflower-bright-twois",
    name: "دسته گل آفتابگردان خالص",
    featured: false,
    category: "sunflower",
    categoryName: "آفتاب‌گردان",
    price: 370,
    description: "دسته‌ای ساده و صمیمی از آفتابگردان‌های تازه با ساقه‌های بلند و برگ‌های سبز — بدون تزئین اضافه، فقط طبیعت ناب. مناسب برای کسانی که سادگی و گرمای خالص را دوست دارند.",
    image: "/assets/sunflower2.jpg",
    tint: "var(--gradient-sun)",
  },
  {
    id: "carnation-white-bouquet",
    name: "دسته گل میخک صورتی و رز سفید",
    featured: false,
    category: "carnation",
    categoryName: "میخک",
    price: 1250,
    description: "ترکیب رمانتیک میخک‌های صورتی پرپر با رزهای سفید کوچک، بابونه‌های بنفش ریز، گل عروس سفید و برگ‌های اکالیپتوس — بسته‌بندی دو رنگ کرم و صورتی، انتخابی دلنشین برای مادران و عزیزان.",
    image: "/assets/carnation2.jpg",
    tint: "linear-gradient(135deg, oklch(0.97 0.03 90), oklch(0.93 0.06 60))",
  },
  {
    id: "carnation-white-pink",
    name: "دسته گل میخک صورتی خالص",
    featured: false,
    category: "carnation",
    categoryName: "میخک",
    price: 760,
    description: "دسته‌ای پر و چشم‌نواز از میخک‌های صورتی دو رنگ با لبه‌های کرم، همراه با گل عروس سفید ظریف — بسته‌بندی شیک با کاغذ بنفش یاسی و لایه داخلی نقره‌ای، هدیه‌ای کلاسیک و پرمحبت.",
    image: "/assets/carnation3.jpg",
    tint: "linear-gradient(135deg, oklch(0.97 0.03 90), oklch(0.93 0.06 60))",
  },
  {
    id: "carnation-white-burgundy-edge",
    name: "دسته گل میخک سفید با لبه‌های زرشکی",
    featured: true,
    category: "carnation",
    categoryName: "میخک",
    price: 950,
    description: "میخک‌های نادر و چشم‌نواز با گلبرگ‌های سفید کرمی و لبه‌های زرشکی تیره — ترکیبی منحصربه‌فرد و اشرافی که کمتر دیده می‌شود. هر گل انگار با دست نقاشی شده، هدیه‌ای متفاوت برای سلیقه‌های خاص.",
    image: "/assets/carnation.jpg",
    tint: "linear-gradient(135deg, oklch(0.97 0.03 90), oklch(0.93 0.06 60))",
  },
  {
    id: "lily-pink-oriental",
    name: "دسته گل لیلیوم اورینتال صورتی",
    featured: false,
    category: "lily",
    categoryName: "لیلیوم",
    price: 380,
    description: "لیلیوم‌های اورینتال درشت و خوشبو با گلبرگ‌های صورتی و سفید خالدار، همراه با گل عروس سفید ظریف و برگ‌های اکالیپتوس تازه — بسته‌بندی ساده و شیک با کاغذ کرافت طبیعی و روبان سفید. عطر دلنشین و ظاهر رویایی‌اش هر فضایی را زیبا می‌کند.",
    image: "/assets/lily1.jpg",
    tint: "linear-gradient(135deg, oklch(0.97 0.03 90), oklch(0.93 0.06 60))",
  },
  {
    id: "lily-pink-white-wrapped",
    name: "دسته گل لیلیوم صورتی با بسته‌بندی سفید",
    featured: true,
    category: "lily",
    categoryName: "لیلیوم",
    price: 530,
    description: "لیلیوم‌های صورتی لطیف با غنچه‌های نیمه‌باز و گل عروس سفید ظریف — بسته‌بندی مجلل با کاغذ سفید مات و روبان دو رنگ صورتی و سفید. ترکیبی پاک و رمانتیک که برای هدیه به عزیزان بی‌نظیر است.",
    image: "/assets/lily2.jpg",
    tint: "linear-gradient(135deg, oklch(0.97 0.03 90), oklch(0.93 0.06 60))",
  },
  {
    id: "lily-white-pure-garden",
    name: "دسته گل لیلیوم سفید خالص",
    featured: false,
    category: "lily",
    categoryName: "لیلیوم",
    price: 280,
    description: "لیلیوم‌های سفید برفی با پرچم‌های طلایی و قهوه‌ای، نمادی از پاکی و معصومیت — شکوفه‌های کاملاً باز در دل سبزه‌های تازه، عطری آرام‌بخش و ظاهری بی‌آلایش. انتخابی ایده‌آل برای مراسم و هدایای رسمی.",
    image: "/assets/lily3.jpg",
    tint: "linear-gradient(135deg, oklch(0.97 0.03 90), oklch(0.93 0.06 60))",
  },
  {
    id: "wedding-rose-luyury-bouquet",
    name: "دسته گل خواستگاری رز پاستلی رویایی",
    featured: true,
    category: "wedding",
    categoryName: "گل خواستگاری",
    price: 1550,
    description: "دسته گل خواستگاری لاکچری با رزهای صورتی پاستلی و بنفش یاسی، رزهای سفید ظریف، گل عروس، شاخه‌های اکالیپتوس و گیاهان وحشی — بسته‌بندی مجلل با لایه‌های کاغذ صورتی پودری و تزئینات قلبی. برای لحظه‌ای که هرگز فراموش نمی‌شود.",
    image: "/assets/weddingFlower.jpg",
    tint: "linear-gradient(135deg, oklch(0.95 0.05 320), oklch(0.85 0.1 300))",
  },
  {
    id: "wedding-rose-chrysanthemum-giant",
    name: "دسته گل خواستگاری غول‌آسای رز و داودی صورتی",
    featured: false,
    category: "wedding",
    categoryName: "گل خواستگاری",
    price: 1700,
    description: "دسته گل خواستگاری باشکوه و غول‌آسا با رزهای کرم صورتی، داودی‌های بنفش پودری و گل عروس صورتی فراوان — ترکیبی یکدست و رویایی در تُن‌های پاستلی، بسته‌بندی مجلل با کاغذ و روبان صورتی پودری. هدیه‌ای که قلب را می‌برد.",
    image: "/assets/weddingFlower2.jpg",
    tint: "linear-gradient(135deg, oklch(0.97 0.03 30), oklch(0.9 0.08 10))",
  },
  {
    id: "wedding-lily-rose-bouquet",
    name: "دسته گل عروس لیلیوم و رز صورتی",
    featured: true,
    category: "wedding",
    categoryName: "گل خواستگاری",
    price: 1400,
    description: "دسته گل عروس اشرافی با لیلیوم‌های صورتی بلند و غنچه‌های باز نشده، رزهای صورتی لطیف، میخک‌های ریز و گل عروس سفید — بسته‌بندی چندلایه با کاغذ صورتی شفاف، کنف طبیعی و تور ابریشمی. انتخابی رویایی برای روز عروسی.",
    image: "/assets/weddingFlower1.jpg",
    tint: "linear-gradient(135deg, oklch(0.97 0.03 30), oklch(0.9 0.08 10))",
  },
];

export const formatAfghani = (n: number) =>
  new Intl.NumberFormat("fa-AF").format(n) + " افغانی";
